name: Run on Excel File Change

on:
  push:
    paths:
      - '*/game_log.xlsx'
      - '*/hitters.xlsx'

jobs:
  process-excel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
        python-version: '3.12'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Process Excel file
        run: python alter_table.py
          
          # Add your script or commands to process the Excel file here